// components/SettingsModal.vue
<template>
  <div v-if="isOpen" class="fixed inset-0 z-50 overflow-y-auto">
    <div class="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
      <div class="fixed inset-0 transition-opacity" aria-hidden="true">
        <div class="absolute inset-0 bg-gray-500 opacity-75" @click="closeModal"></div>
      </div>

      <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
        <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
          <div class="sm:flex sm:items-start">
            <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left w-full">
              <h3 class="text-lg leading-6 font-medium text-gray-900 mb-4">Settings</h3>
              
              <div class="mt-4">
                <h4 class="text-md font-medium text-gray-700 mb-2">Instruments</h4>
                
                <div class="flex items-center mb-4">
                  <input 
                    type="text" 
                    v-model="newInstrument" 
                    placeholder="Add new instrument" 
                    class="shadow-sm focus:ring-blue-500 focus:border-blue-500 block w-full sm:text-sm border-gray-300 rounded-md mr-2"
                  />
                  <button 
                    @click="addInstrument" 
                    class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                  >
                    Add
                  </button>
                </div>
                
                <ul class="divide-y divide-gray-200">
                  <li 
                    v-for="instrument in instruments" 
                    :key="instrument" 
                    class="py-2 flex justify-between items-center"
                  >
                    <span>{{ instrument }}</span>
                    <button 
                      @click="deleteInstrument(instrument)" 
                      class="text-red-600 hover:text-red-800"
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                      </svg>
                    </button>
                  </li>
                </ul>
              </div>
              
              <div class="mt-6">
                <h4 class="text-md font-medium text-gray-700 mb-2">Data Management</h4>
                <div class="flex space-x-2">
                  <button 
                    @click="exportData" 
                    class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                  >
                    Export Data
                  </button>
                  <label class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 cursor-pointer">
                    Import Data
                    <input 
                      type="file" 
                      @change="importData" 
                      accept=".json" 
                      class="hidden"
                    />
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
          <button 
            @click="closeModal" 
            class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import { useStudentStore } from '~/stores/student';
import { useUIStore } from '~/stores/ui';
import { storeToRefs } from 'pinia';

// Initialize stores
const studentStore = useStudentStore();
const uiStore = useUIStore();

// Get reactive state from stores
const { instruments } = storeToRefs(studentStore);
const { settingsModalOpen } = storeToRefs(uiStore);

// Local state
const newInstrument = ref('');

// Computed properties
const isOpen = computed(() => settingsModalOpen.value);

// Methods
function closeModal() {
  uiStore.setSettingsModalOpen(false);
}

function addInstrument() {
  if (newInstrument.value.trim()) {
    studentStore.addInstrument(newInstrument.value.trim());
    newInstrument.value = '';
  }
}

function deleteInstrument(instrument) {
  if (process.client && confirm(`Are you sure you want to delete the instrument "${instrument}"?`)) {
    studentStore.deleteInstrument(instrument);
  }
}

function exportData() {
  studentStore.exportData();
}

function importData(event) {
  if (!process.client) return;
  
  const file = event.target.files[0];
  if (!file) return;
  
  const reader = new FileReader();
  reader.onload = (e) => {
    try {
      const data = JSON.parse(e.target.result);
      
      if (data.students) {
        studentStore.setStudents(data.students);
      }
      
      if (data.settings) {
        studentStore.setSettings(data.settings);
      }
      
      alert('Data imported successfully!');
    } catch (error) {
      console.error('Import error:', error);
      alert('Error importing data. Please check the file format.');
    }
  };
  
  reader.readAsText(file);
  event.target.value = null; // Reset the input
}
</script>

// app/features/dashboard/modals/SettingsModal.tsx
'use client'

import { useState, useRef } from 'react'
import { useStudentStore } from '@/store/useStudentStore'
import { useUIStore } from '@/store/useUIStore'
import Modal from '@/app/components/modals/Modal'

// CSS variables for standardization
const styles = {
  button: {
    primary: "rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2",
    secondary: "rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2",
    danger: "text-red-600 hover:text-red-800",
  },
  section: {
    title: "text-lg font-semibold text-gray-900 dark:text-white mb-4",
    subtitle: "text-sm font-medium text-gray-700 dark:text-gray-300 mb-2",
    container: "space-y-6",
    divider: "border-t border-gray-200 dark:border-gray-700 pt-5 mt-2",
  },
  input: {
    base: "block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500",
    error: "border-red-500",
  },
  listItem: "flex justify-between items-center bg-gray-50 p-2 rounded",
  text: {
    error: "mt-1 text-sm text-red-600",
    muted: "text-gray-500 italic",
  },
  spacing: {
    standard: "space-x-3",
  }
}

export default function SettingsModal() {
  const isOpen = useUIStore(state => state.settingsModalOpen)
  const setIsOpen = useUIStore(state => state.setSettingsModalOpen)
  
  const { settings, addInstrument, deleteInstrument, exportData, setStudents, setSettings } = useStudentStore()
  
  const [newInstrument, setNewInstrument] = useState('')
  const [error, setError] = useState('')
  
  const fileInputRef = useRef<HTMLInputElement | null>(null)
  
  const handleAddInstrument = () => {
    if (!newInstrument.trim()) {
      setError('Instrument name is required')
      return
    }
    
    const trimmedInstrument = newInstrument.trim()
    
    if (settings.instruments.includes(trimmedInstrument)) {
      setError('This instrument already exists')
      return
    }
    
    addInstrument(trimmedInstrument)
    setNewInstrument('')
    setError('')
  }
  
  const handleDeleteInstrument = (instrument: string) => {
    if (window.confirm(`Are you sure you want to delete "${instrument}"?`)) {
      deleteInstrument(instrument)
    }
  }
  
  const handleExportData = () => {
    exportData()
  }
  
  const handleImportData = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    const reader = new FileReader()
    reader.onload = (event) => {
      try {
        const data = JSON.parse(event.target?.result as string)
        if (data.students && data.settings) {
          setStudents(data.students)
          setSettings(data.settings)
          alert('Data imported successfully!')
        } else {
          alert('Invalid data format')
        }
      } catch (error: any) {
        alert('Failed to import data: ' + error.message)
      }
    }
    reader.readAsText(file)
  }
  
  const openFileDialog = () => {
    fileInputRef.current?.click()
  }
  
  const handleClose = () => {
    setIsOpen(false)
    setNewInstrument('')
    setError('')
  }
  
  return (
    <Modal isOpen={isOpen} onClose={handleClose} title="Settings">
      <div className={styles.section.container}>
        <div>
          <h3 className={styles.section.title}>Instruments</h3>
          
          <div className="flex items-start mb-4">
            <div className="flex-grow mr-2">
              <input
                type="text"
                value={newInstrument}
                onChange={(e) => {
                  setNewInstrument(e.target.value)
                  if (error) setError('')
                }}
                className={`${styles.input.base} ${
                  error ? styles.input.error : ''
                }`}
                placeholder="Add new instrument..."
              />
              {error && <p className={styles.text.error}>{error}</p>}
            </div>
            <button
              type="button"
              onClick={handleAddInstrument}
              className={styles.button.primary}
            >
              Add
            </button>
          </div>
          
          <div className="mt-4">
            <h4 className={styles.section.subtitle}>Current Instruments:</h4>
            {settings.instruments.length === 0 ? (
              <p className={styles.text.muted}>No instruments added yet</p>
            ) : (
              <ul className="space-y-2">
                {settings.instruments.map(instrument => (
                  <li key={instrument} className={styles.listItem}>
                    <span>{instrument}</span>
                    <button
                      onClick={() => handleDeleteInstrument(instrument)}
                      className={styles.button.danger}
                    >
                      Delete
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
        
        <div className={styles.section.divider}>
          <h3 className={`${styles.section.title} text-xl`}>Data Management</h3>
          
          <div className={`flex ${styles.spacing.standard}`}>
            <button
              type="button"
              onClick={handleExportData}
              className={styles.button.secondary}
            >
              Export Data
            </button>
            
            <button
              type="button"
              onClick={openFileDialog}
              className={styles.button.secondary}
            >
              Import Data
            </button>
            <input
              type="file"
              ref={fileInputRef}
              onChange={handleImportData}
              accept="application/json"
              style={{ display: 'none' }}
            />
          </div>
        </div>
        
        <div className={`flex justify-end ${styles.section.divider}`}>
          <button
            type="button"
            onClick={handleClose}
            className={styles.button.primary}
          >
            Close
          </button>
        </div>
      </div>
    </Modal>
  )
}
