// components/AddStudentModal.vue
<template>
  <div v-if="isOpen" class="fixed inset-0 z-50 overflow-y-auto">
    <div class="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
      <div class="fixed inset-0 transition-opacity" aria-hidden="true">
        <div class="absolute inset-0 bg-gray-500 opacity-75" @click="closeModal"></div>
      </div>

      <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
        <form @submit.prevent="saveStudent">
          <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
            <div class="sm:flex sm:items-start">
              <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left w-full">
                <h3 class="text-lg leading-6 font-medium text-gray-900 mb-4">Add New Student</h3>
                
                <div class="grid grid-cols-1 gap-4">
                  <div>
                    <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
                    <input 
                      type="text" 
                      id="name" 
                      v-model="form.name" 
                      required
                      class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                    />
                  </div>
                  
                  <div>
                    <label for="instrument" class="block text-sm font-medium text-gray-700">Instrument</label>
                    <select 
                      id="instrument" 
                      v-model="form.instrument" 
                      required
                      class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                    >
                      <option value="" disabled>Select an instrument</option>
                      <option v-for="instrument in instruments" :key="instrument" :value="instrument">
                        {{ instrument }}
                      </option>
                    </select>
                  </div>
                  
                  <div>
                    <label for="grade" class="block text-sm font-medium text-gray-700">Grade</label>
                    <select 
                      id="grade" 
                      v-model="form.grade" 
                      required
                      class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                    >
                      <option value="" disabled>Select a grade</option>
                      <option value="Beginner">Beginner</option>
                      <option value="Grade 1">Grade 1</option>
                      <option value="Grade 2">Grade 2</option>
                      <option value="Grade 3">Grade 3</option>
                      <option value="Grade 4">Grade 4</option>
                      <option value="Grade 5">Grade 5</option>
                      <option value="Grade 6">Grade 6</option>
                      <option value="Grade 7">Grade 7</option>
                      <option value="Grade 8">Grade 8</option>
                      <option value="Advanced">Advanced</option>
                    </select>
                  </div>
                  
                  <div>
                    <label for="day" class="block text-sm font-medium text-gray-700">Lesson Day</label>
                    <select 
                      id="day" 
                      v-model="form.day" 
                      required
                      class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                    >
                      <option value="" disabled>Select a day</option>
                      <option value="Monday">Monday</option>
                      <option value="Tuesday">Tuesday</option>
                      <option value="Wednesday">Wednesday</option>
                      <option value="Thursday">Thursday</option>
                      <option value="Friday">Friday</option>
                      <option value="Saturday">Saturday</option>
                      <option value="Sunday">Sunday</option>
                    </select>
                  </div>
                  
                  <div>
                    <label for="time" class="block text-sm font-medium text-gray-700">Lesson Time</label>
                    <input 
                      type="time" 
                      id="time" 
                      v-model="form.time" 
                      required
                      class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
            <button 
              type="submit" 
              class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-blue-600 text-base font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 sm:ml-3 sm:w-auto sm:text-sm"
            >
              Save
            </button>
            <button 
              type="button" 
              @click="closeModal" 
              class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import { useStudentStore } from '~/stores/student';
import { useUIStore } from '~/stores/ui';
import { storeToRefs } from 'pinia';

const studentStore = useStudentStore();
const uiStore = useUIStore();

const { instruments } = storeToRefs(studentStore);
const { addStudentModalOpen } = storeToRefs(uiStore);

const form = ref({
  name: '',
  instrument: '',
  grade: '',
  day: '',
  time: ''
});

const isOpen = computed(() => addStudentModalOpen.value);

function closeModal() {
  uiStore.setAddStudentModalOpen(false);
  resetForm();
}

async function saveStudent() {
  await studentStore.createStudent({ ...form.value });
  closeModal();
}

function resetForm() {
  form.value = {
    name: '',
    instrument: '',
    grade: '',
    day: '',
    time: ''
  };
}
</script>

// app/components/modals/AddStudentModal.tsx
import { useState } from 'react'
import { useUIStore } from '../../store/useUIStore'
import { useStudentStore } from '../../store/useStudentStore'
import { Dialog } from '@headlessui/react'
import { Student } from '../../../lib/types'

export default function AddStudentModal() {
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  
  const { isAddStudentModalOpen, closeAddStudentModal } = useUIStore()
  const addStudent = useStudentStore(state => state.addStudent)
  
  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    setIsSubmitting(true)
    setError(null)
    
    console.group('🎓 Adding New Student')
    console.log('📝 Starting form submission process...')
    
    const formData = new FormData(e.currentTarget)
    const studentData: Partial<Student> = {
      name: formData.get('name') as string,
      grade: formData.get('grade') as string,
      attendance: '100%',
      lastActive: 'Today',
    }
    
    console.log('📋 Collected form data:', {
      name: studentData.name,
      grade: studentData.grade,
      attendance: studentData.attendance,
      lastActive: studentData.lastActive
    })
    
    try {
      console.log('🚀 Sending request to create student...')
      console.time('createStudent')
      
      const response = await fetch('/api/students', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(studentData),
      })
      
      const data = await response.json()
      console.timeEnd('createStudent')
      
      if (!response.ok) {
        console.error('❌ Server returned error:', data.error)
        throw new Error(data.error || 'Failed to create student')
      }
      
      console.log('✅ Student created successfully:', {
        _id: data._id,
        name: data.name,
        grade: data.grade
      })
      
      // Update local state with the complete student data from MongoDB
      addStudent(data)
      console.log('📊 Local state updated with new student')
      
      // Close modal and reset form
      e.currentTarget.reset()
      closeAddStudentModal()
      console.log('🔒 Add student modal closed')
      console.groupEnd()
      
    } catch (err) {
      console.group('❌ Error Details')
      console.error('Error creating student:', err)
      console.error('Stack trace:', err instanceof Error ? err.stack : 'No stack trace available')
      console.groupEnd()
      
      setError(err instanceof Error ? err.message : 'Failed to create student')
    } finally {
      setIsSubmitting(false)
    }
  }
  
  return (
    <Dialog
      open={isAddStudentModalOpen}
      onClose={closeAddStudentModal}
      className="relative z-50"
    >
      {/* Backdrop */}
      <div className="fixed inset-0 bg-black/30" aria-hidden="true" />
      
      {/* Full-screen container */}
      <div className="fixed inset-0 flex items-center justify-center p-4">
        <Dialog.Panel className="w-full max-w-md rounded-lg bg-white dark:bg-gray-800">
          <Dialog.Title className="p-6 border-b border-gray-200 dark:border-gray-700">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Add New Student</h3>
          </Dialog.Title>
          
          <form onSubmit={handleSubmit} className="p-6 space-y-4">
            <div>
              <label htmlFor="name" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Student Name
              </label>
              <input
                type="text"
                name="name"
                id="name"
                required
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
              />
            </div>
            
            <div>
              <label htmlFor="grade" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Grade
              </label>
              <select
                name="grade"
                id="grade"
                required
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
              >
                <option value="A+">A+</option>
                <option value="A">A</option>
                <option value="A-">A-</option>
                <option value="B+">B+</option>
                <option value="B">B</option>
                <option value="B-">B-</option>
                <option value="C+">C+</option>
                <option value="C">C</option>
                <option value="C-">C-</option>
                <option value="D">D</option>
                <option value="F">F</option>
              </select>
            </div>
            
            {error && (
              <div className="text-red-500 text-sm">
                {error}
              </div>
            )}
            
            <div className="mt-6 flex justify-end space-x-3">
              <button
                type="button"
                onClick={closeAddStudentModal}
                className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="inline-flex justify-center px-4 py-2 text-sm font-medium text-white bg-indigo-600 border border-transparent rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
              >
                {isSubmitting ? 'Adding...' : 'Add Student'}
              </button>
            </div>
          </form>
        </Dialog.Panel>
      </div>
    </Dialog>
  )
}
